#!/usr/bin/env python

# Quicli: Zero-effort CLI generation.
#
# To use on an unmodified script, run quicli in place of the Python
# intepreter. See the README file for more details.

import sys
sys.argv = sys.argv[1:]
exec(open(sys.argv[0]).read())

import quicli
quicli.main()
