#!/usr/bin/env python
import quarg

@quarg.command
def prod(x,y = 1):
    return int(x) * y

@quarg.command
def sum(x, y = 0):
    return int(x) + y

def div(x, y = 1):
    return int(x) / y

quarg.main()
