#!/usr/bin/env python
import quicli

@quicli.command
def prod(x,y = 1):
    return int(x) * y

@quicli.command
def sum(x, y = 0):
    return int(x) + y

def div(x, y = 1):
    return int(x) / y

quicli.main()
